### ISSUE TITLE
Today Extension

### ISSUE THREAD

**Issue by mattbarker016** [cuappdev/ithaca-transit-ios#147]
# Goal

Create a Today Extension that provides meaningful information about a user's favorite stops.

*Original Design Mockups*
<img width="809" alt="image" src="https://user-images.githubusercontent.com/8039928/45936182-a386b180-bf81-11e8-9c0e-189e2d64e482.png">

Designs are on Zeplin and can be found [here](https://app.zeplin.io/project/59df842e332ecf6acddf3ef3/dashboard?seid=5ba820971ca4575f401fa298).

# Task Breakdown

### Initial Today Extension Setup
- [x] **Create a Today Extension within the Xcode project.**
- [x] **Allow for shared data.** Use user groups (e.g. `"group.tcat"`) to access `UserDefaults` between main app and extension. *Note:* We may not need this presently, but we should set up the infrastructure to share data between targets.
- [x] **Create UITableView setup that works in collapsed and expanded mode.** Use a dummy blank `UITableViewCell()` for now. The view should show 1 cell when minimized and up to 5 favorites (or however many that can fit within the max height of the extension).

### Networking
- [x] Add getMultiRoute() function to Network.swift.** Use the typical TRON format to create this function, and write similar functionality to process the data **in Codable.**

### TodayExtensionCell
- [x] **Create a UITableViewCell class for the view's cell.** Should include relevant data variables, relevant subviews, proper constraints setup, etc.

### UITableView Functions
- [x] `cellForRowAtIndexPath`: Add your custom UITableViewCell here.
- [x] `didSelectCellAtIndexPath`: Trigger the URL scheme code to open the app here. You should be able to use `extensionContext.open(...)`.

# Potential Blockers

**Backend** implemented a multi-route endpoint so we can querying information about favorite bus stops in one request. See [#56](https://github.com/cuappdev/ithaca-transit-backend/issues/56) on [ithaca-transit-backend](https://github.com/cuappdev/ithaca-transit-backend) for the specs and issue. This was merged, and should be within the revamped backend. Check with @JunyoungLim on this.
